sudo: required
language: python
addons:
  firefox: latest
env:
  global:
    - MOZ_HEADLESS=1
    - BASE_URL="http://localhost:5500/"

services:
  - docker

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.21.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin

script:
  - whereis firefox
  - make run
  - make stop

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: pages
  target_branch: gh-pages
  local_dir: src
  skip_cleanup: true
  github_token:
    secure: aOQVIn4pCEjtabYHwdJwpKV/kk9ez+Azr3LrNhykS8kpnNowyzP3ALRZSyvW+GtngeVb52dyPn6RuEPLPGZdRaojz+PzD+utQfVzriE4aPM+h/9+HBp4TeS/LNok81gy/TDQa0hAgVrscPnV3dZzSqA5kr2suT+EI+MJNu4rxtGxBM/JP+j9FCGueapa/tO4IW9+2BsIzcEKidOxZRQRrUC6qygLsU/SHTIWewMZTVFpsm33MtFtVV1g5uTx2fUeIi5O/L5EybLHvBQ659FDYpdIcP3pOC2jdLAGtNBVM1/3TzqF1KnE9Lw7qXFF8fBx7BKxFgdtqmWqXeYufBWJB2qRE32xYW9V2h8CKb/sH2yyqHPftbworu2IuAv911xqlWE2Dv4RXtsgfDgsF6V8AxfEPOsCv4zQRx5haHaf2TJe0yTm2jLzhul67D8kkgLwZanL4i0mxvsrharCZSxK5AfvRtX4Cc58bCybcopnQsTFh2P7pJeQ1K6gZ3xZEND9WQPngPx3gT8csH67r16PQefpg8EvonkwFTopOK6Ur2hn+ZsbBIsG38q59rkEEi74X29xyxltRK3/eStNkmr3u8zuBgC4r3FoNBOuwDXMbMtc/eLhIro6sm6PA0YfSm9efoSdXLV/dYR/bS5SBNpdluTDGmBRCwWrSmtvVr1dOVE=
  keep_history: true
  verbose: true
  on:
    branch: build

notifications:
  slack:
    rooms:
      secure: "45VhQ6CEmS/SyriKTuzlHkT3hjFkzUW+MPEHjwxGd19mkHxN3LO86T9ZGkNSSuRahc4W5esHW4SAfB9P0X/3NDCvoMj/PiGCVZ1Q/BSatnWMm4ScG88OAiW6JfqPV4Hh7S3rpXwXYlcFNDOkAt6RSFJmVxz6U43t/xm2INHFfWJxFyt/aObXWXsO3iacJVX0sCsAdxh0/DuxbIGvQoM0wyBO+PxSOJfIK5/z1Bowuax4hVbt6LIlJIHQBywGYN8vmhmfL8bzsy1xDBofthmaRbXVHaeGaXKBRsJo/6u5JOMrINyIpFO2boz7R6Id4wtFYuQRYa5FXRKRTex7Z6wH6S1RGtbWO0fVIqdxdTHrv8l3jQlI3GLZYYe6pHJfnIVLYAc7nHROKaiE5D2uW270SqDCp84ht2rcNYwEgdHXAgEU/kVebjTMti5GmBbXXXLBCix8Ew/Lkfo4hRm30a0mnMLuSrQZ3v8BBIAa0KNz/0v+PFCgzZBfsXtv2jcV2BOEH4JzfKZ9sxa3xLIhYi0hm0Eh1bsbVLkWv0ykbGED7bjxM5sWbFVwtBLL6xSRLfOK9uvhh/AW6lRZGKv2XCDg3GHmivkYhkFblaQWS/Ltd0G8/JlA7RV+DqN7VMqGKRf6A9W28Wyy7eC/095o+y8v+MTTzC4bhy2uoXlYIPpU/54="
